title = "RuiXiao85.Net"
theme = ["heyo-hugo-theme", "hugo-shortcode-gallery"]
baseURL = "."
languageCode = "en"
DefaultContentLanguage = "en"
summarylength = 100
enableEmoji = true
enableRobotsTXT = true
paginate = 10

# Disqus comments
# https://gohugo.io/templates/internal/#configure-disqus
# disqusShortname = ""

# Google Analytics
# https://gohugo.io/templates/internal/#google-analytics
# googleAnalytics = ""

[Languages]
  [Languages.en]
    contentDir = "content/en"
    weight = 1
    LanguageName = "en"

  [Languages.cn]
    contentDir = "content/cn"
    weight = 2
    LanguageName = "中文"

[params.author]
  name = "Rui Xiao"
  email = "ruixiao85@gmail.com"

[params]
  title = "Rui Xiao, Ph.D."
  description = "Call me Rui (Ray)"
  profilePicture = "images/Xiao.jpg"
  favicon = "favicons/"
  customCss = []
  customJs = []
  displayMode = "light"
  images = ['images/Xiao.jpg']

[taxonomies]
  series = 'series'
  categories = 'categories'
  tags = 'tags'

# Sketch settings
# you can also enable or disable it per page
[params.sketch]
  enable = true
  displayOptions = false
  # Graph, Digital Rain, or Circles
  use = "Digital Rain"
  # JSON that is passed to the sketch constructor
  # You can check all the possible configurations in
  startingConfig = """{
    "kind": "random",
    "nStreams": 10
  }"""


## Math settings
[params.math]
  # global support, you can also configure it per page
  enable = true
  # katex or mathjax, default is mathjax
  use = "mathjax"

## Social links
[[params.socialIcons]]
icon = "fab fa-linkedin" # Font-awesome icon
title = "Linkedin"
url = "https://www.linkedin.com/in/rui-xiao-3b4a4859"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/ruixiao85"

# [[params.socialIcons]]
# icon = "fab fa-instagram"
# title = "instagram"
# url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:ruixiao85@gmail.com"

# Menu items
[menu]
[[Languages.en.menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/en/"

[[Languages.en.menu.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/post/"

[[Languages.en.menu.main]]
name = "About"
weight = 300
identifier = "about"
url = "/about/"

[[Languages.cn.menu.main]]
name = "主页"
identifier = "home"
weight = 100
url = "/cn/"

[[Languages.cn.menu.main]]
name = "贴文"
weight = 200
identifier = "posts"
url = "/post/"

[[Languages.cn.menu.main]]
name = "关于"
weight = 300
identifier = "about"
url = "/about/"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 1
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

# Hugo will ignore these files, .rmd and .rmarkdown are taken care by blogdown
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]
